
import "./globals.css";
import { Header } from "@/components/common/Header";
import { Footer } from "@/components/common/Footer";
import { Analytics } from "@vercel/analytics/next";



export const metadata = {
  title: "AniCare - Animal Care",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html
      lang="en"
      className={ `h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">
        <Header />
      
        {children}
        <Footer />
        <Analytics />
        </body>
    </html>
  );
}
